### ISSUE TITLE
RC05, RC06, RC07 crashes when re-initializing state

### ISSUE THREAD

**Issue by cacfd3a** [Syer10/voyager#4]
I will tell you how to reproduce. Here is sample code: [crash-sample.zip](https://github.com/Syer10/voyager/files/10299138/crash-sample.zip)

1. Make sure you have old Logcat enabled, so that we may simulate system killing of the app. This app kill *must* be done with the old Logcat button, since all other 'stop' buttons mean something different, and Google engineers have not ported this functionality to any other affordance. See [249950445](https://issuetracker.google.com/issues/249950445) for more information. Enable old Logcat through: Settings > Experimental > unselect 'Enable new Logcat'
2. Use `ca.gosyer:voyager-navigator:1.0.0-rc05+`
3. Open App with nested Navigator, as provided in the sample code
4. Navigate to sub-post
5. Background the app
6. Use the 'Terminate Application' button in the left-hand pane of the old Logcat screen, then foreground the app again. This simulated the situation in the wild where the app is backgrounded ~30m, and then terminated by the system, then reopened
8. \*crash\*

```
2022-12-24 21:49:27.949 9817-9817/com.example.voyagersample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.voyagersample, PID: 9817
    java.lang.IllegalArgumentException: Key Screen#1:currentScreen:lifecycle was used multiple times 
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
        at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1091)
        at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:978)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
        at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1060)
        at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
        at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
        at android.view.View.dispatchAttachedToWindow(View.java:21290)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2820)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:832)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

I can't make a screencast while the emulator is running, so I've made a screencast on my phone. See attachment.

![image](https://user-images.githubusercontent.com/178797/209450968-ed2eca7b-a3e8-4eea-8399-c2305138a1e7.png)

Perhaps this has something to do with the screens being re-created with 'unique' screen id's, that are not  unique anymore since the AtomicInt counter is reset when the app is killed? I do not understand how this SavedState business works. 🤷

Perhaps related to #2? I also don't understand what's going on _there_...
[crash-sample.zip](https://github.com/Syer10/voyager/files/10299134/crash-sample.zip)

https://user-images.githubusercontent.com/178797/209450977-9e9dcf84-bb43-4e14-94f7-a93d39c9418d.mp4

edit: oops, I meant the text to appear only when the app was backgrounded, of course :D

**Comment by Syer10** [comment]
I can reporoduce this, I'll see what I can do

**Comment by cacfd3a** [comment]
I've tried affixing a timestamp to `uniqueScreenKey`, logging each time it gets set, and also logging each call of SaveableStateProvider:

```
"Screen#${nextScreenKey.getAndIncrement()}-${uptimeMillis()}".also { android.util.Log.e("BeW", "Unique screen key: $it") }
```

``` Unique screen key: Screen#0-219538793
 SaveableStateProvider(Screen#0-219538793:currentScreen)
 Unique screen key: Screen#1-219539277
 SaveableStateProvider(Screen#0-219538793:currentScreen)
 Unique screen key: Screen#2-219542251
 Unique screen key: Screen#3-219542251
 SaveableStateProvider(Screen#3-219542251:currentScreen)
 --- app terminated & restarted ---
 Unique screen key: Screen#0-219552529
 Unique screen key: Screen#1-219552554
 SaveableStateProvider(Screen#0-219552529:currentScreen)
 Unique screen key: Screen#2-219552643
 SaveableStateProvider(Screen#0-219552529:currentScreen)
 SaveableStateProvider(Screen#0-219538793:currentScreen)
```

Indeed this mititgates the issue since the clock monotonically grows, and there are no clashes anymore with 'Screen#0'. But I don't understand why `Screen` should not parcelize the key value? I can't make sense of what's going on here.

**Comment by Syer10** [comment]
Ok I have found the main reason. Basically in rememberNavigator it wasnt properly saving all navigators, only the first one because the function made every navigator use the same key. Adding `key = "navigator_${parent?.level ?: 0}"` to rememberSaveable has helped, but now for some reason the BackHandler fires immediently even though its loading the nested navigators screen.

**Comment by Syer10** [comment]
Also the AtomicInt starting from 0 is an issue as well that will need to be considered

**Comment by cacfd3a** [comment]
> BackHandler fires immediently even though its loading the nested navigators screen.

Really? I don't notice it

> `"navigator_${parent?.level ?: 0}"`

Is this strictly correct? If the top Navigator has multiple sub-navigators, will they not be all on the same level? Perhaps there should also be a counting mechanism for Navigators.

> Also the AtomicInt starting from 0 is an issue as well that will need to be considered

Screen keys are not parcelized, apparently, so the counter starting afresh does not need to matter, since all screen keys are forgotten. I thought `@Parcelize` parceled all properties that are not marked as `@IgnoredOnParcel`, but:

> the code generated by `@Parcelize` doesn't care about the superclass at all.

[Src](https://stackoverflow.com/a/61776907)

So I suppose it's not a problem unless one makes the screen key persistent. 

Happy holidays!

**Comment by Syer10** [comment]
> Really? I don't notice it

It only happens when I do end up with a working version somehow

> Is this strictly correct? If the top Navigator has multiple sub-navigators, will they not be all on the same level? Perhaps there should also be a counting mechanism for Navigators.

Good point, I will look for an alternate way to do this

> Screen keys are not parcelized, apparently, so the counter starting afresh does not need to matter, since all screen keys are forgotten.

Screens are Serializable, not Parcable by default. And the screen keys do get serialized, but the issue here was that the way saving the screens worked, it tried to restore the same screens multiple times. Fixing this means that the screens get the old keys back, but this also opens the issue of AtomicInt starting from 0 again, and screens will conflict if they do end up with the same key.

**Comment by Syer10** [comment]
I'm back to using the main version of Voyager, I am closing all issues because of this.
